"""empty message

Revision ID: 33ef1cefb25c
Revises: 978d421ef128
Create Date: 2025-09-30 14:07:01.298126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ef1cefb25c'
down_revision: Union[str, Sequence[str], None] = '978d421ef128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('intent', sa.Enum('buy', 'support', 'spam', 'job', 'other', name='intent_enum'), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='priority_enum'), nullable=False),
    sa.Column('next_action', sa.Enum('call', 'email', 'ignore', 'qualify', name='next_action_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_insight_confidence_range'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_lead_id'), 'insights', ['lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insights_lead_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_table('leads')
    op.drop_table('keys')
    # ### end Alembic commands ###
